import DocumentHead from "next/head"

export const Head = () => {
  return (
    <DocumentHead>
      <title>Rated Test Task</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />

      <link rel="icon" href="favicon.png" />
    </DocumentHead>

  )
} 
